import { Download } from 'lucide-react'

// Patch CSS/JS and metrics come from peers (potentially untrusted ones) and
// get embedded into the exported HTML report. Escape before interpolating
// so a patch containing something like `</pre><script>...` can't execute
// when someone opens the exported file later.
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export default function ExportButton({ metrics, roomId, peers, patches }) {
  const handleExport = () => {
    const report = {
      tool: 'Synerdio',
      version: '0.1.0',
      exportedAt: new Date().toISOString(),
      roomId,
      peerCount: Object.keys(peers || {}).length + 1,
      metrics,
      patches: (patches || []).map((p) => ({
        id: p.id,
        description: p.description,
        requester: p.requester,
        css: p.css,
        js: p.js,
      })),
    }

    const safeRoomId = escapeHtml(roomId)
    const safeMetricsJson = escapeHtml(JSON.stringify(metrics, null, 2))
    const safePatchesJson = escapeHtml(JSON.stringify(report.patches, null, 2))

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Synerdio Report — ${safeRoomId}</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, sans-serif; background: #0B0F19; color: #e2e8f0; padding: 2rem; max-width: 800px; margin: 0 auto; }
    h1 { color: #00F0FF; }
    pre { background: #121826; padding: 1rem; border-radius: 8px; overflow: auto; border: 1px solid rgba(0,240,255,0.15); }
    .meta { color: #94A3B8; font-size: 0.875rem; }
  </style>
</head>
<body>
  <h1>Synerdio Investigation Report</h1>
  <p class="meta">Room <strong>${safeRoomId}</strong> · ${escapeHtml(report.exportedAt)}</p>
  <h2>Metrics Snapshot</h2>
  <pre>${safeMetricsJson}</pre>
  <h2>Applied Patches</h2>
  <pre>${safePatchesJson}</pre>
  <p class="meta">Generated by Synerdio — collaborative live debugger</p>
</body>
</html>`

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `synerdio-report-${roomId}.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-1.5 text-sm px-3 py-1.5 rounded-lg bg-midnight-lighter border border-cyan/20 hover:border-cyan/40 text-slate hover:text-white transition"
    >
      <Download className="w-3.5 h-3.5" />
      Export Report
    </button>
  )
}